all: conc3_1 conc3_2

conc3_1: diningPhilosophers.c
	gcc diningPhilosophers.c -lpthread -std=c99 -w -o diningPhilosophers

conc3_2: xyz.c
	gcc xyz.c -lpthread -std=c99 -w -o xyz


.PHONY: all show clean ps pdf showps
